import React from 'react';
import Layout from '@/components/Layout';
import GlassCard from '@/components/GlassCard';
import AnimatedTitle from '@/components/AnimatedTitle';
import { useAuth } from '@/contexts/AuthContext';
import { Key, Lock, Unlock, Shield } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';

const Home = () => {
  const { isAuthenticated } = useAuth();

  const features = [
    {
      title: 'RSA Encryption',
      description: 'RSA uses a public key for encryption and a private key for decryption. The algorithm relies on the practical difficulty of factoring the product of two large prime numbers.',
      icon: Shield,
      link: '/key-generation'
    },
    {
      title: 'Key Generation',
      description: 'RSA keys are generated by selecting two large prime numbers and computing their product. The public key includes this product and an encryption exponent.',
      icon: Key,
      link: '/key-generation'
    },
    {
      title: 'Security Aspects',
      description: 'RSA security depends on the mathematical challenge of factoring large numbers. With sufficient key length, RSA is considered secure against conventional computing attacks.',
      icon: Lock,
      link: '/encryption'
    },
    {
      title: 'Real-world Applications',
      description: 'RSA is widely used in secure communications, digital signatures, secure email, SSL/TLS for web security, and various authentication systems.',
      icon: Unlock,
      link: '/decryption'
    }
  ];

  return (
    <Layout isLoggedIn={isAuthenticated}>
      {/* Hero Section */}
      <section className="pt-20 pb-24 flex flex-col items-center justify-center min-h-[70vh]">
        <div className="max-w-4xl mx-auto text-center mb-12">
          <AnimatedTitle subtitle="Secure RSA Cryptography Tool">
            RSA Shield
          </AnimatedTitle>
          
          <p className="text-lg text-white/80 mt-8 mb-12 max-w-2xl mx-auto leading-relaxed">
            A modern, secure platform for RSA encryption and decryption. 
            Generate keys, encrypt sensitive messages, and decrypt them with ease.
          </p>
          
          <div className="flex flex-wrap justify-center gap-4">
            <Button 
              asChild
              variant="primary"
              className="rounded-full"
            >
              <Link to="/key-generation">
                Generate Keys
              </Link>
            </Button>
            <Button 
              asChild
              variant="outline"
              className="rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-white hover:bg-white/20"
            >
              <Link to={isAuthenticated ? "/account" : "/auth"}>
                {isAuthenticated ? 'My Account' : 'Sign Up'}
              </Link>
            </Button>
          </div>
        </div>
      </section>
      
      {/* Features Grid */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-16 text-gradient">How RSA Works</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <Link to={feature.link} key={index}>
                <GlassCard hover className="h-full transition-all duration-300">
                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded-lg bg-primary/10 text-primary">
                      <feature.icon className="h-6 w-6" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                      <p className="text-white/70 leading-relaxed">{feature.description}</p>
                    </div>
                  </div>
                </GlassCard>
              </Link>
            ))}
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default Home;
